### ISSUE TITLE
url fail

### ISSUE THREAD

**Issue by rwoerde** [rnuske/vegperiod#1]
> x <- read.DWDdata(id = 1270, type = "climate", period = "recent", resolution = "monthly")/

Fehlermeldung:

> versuche URL 'ftp://ftp-cdc.dwd.de/pub/CDC/observations_germany/climate/monthly/kl/recent///*monatswerte_01270_akt.zip'*//
//cannot open URL 'ftp://ftp-cdc.dwd.de/pub/CDC/observations_germany/climate/monthly/kl/recent/monatswerte_01270_akt.zip': FTP status was '550 Requested action not taken; file unavailable'Fehler in value[[3L]](cond) : //
//  Could not download file. Try the URL ‘ftp://ftp-cdc.dwd.de/pub/CDC/observations_germany/climate/monthly/kl/recent/monatswerte_01270_akt.zip’ in a Web-Browser. //
//Please inform the package maintainer if you did not use the 'url' argument but the URL is malformed anyway./

Ich informiere Dich hiermit. Die Monatswerte haben jetzt folgende URL

/ftp://ftp-cdc.dwd.de/pub/CDC/observations_germany/climate/monthly/kl/recent//*/monatswerte_KL_01270_akt.zip/

*Hast Du geplant auch die regionalen Mittelwerte o.ä. mit aufzunehmen in den Datenabruf?

**Comment by rnuske** [comment]
DWD changed the file name schema for recent monthly climate data. It was different from the other downloads before and is now harmonized with the rest.

Thanks for reporting @rwoerde.
Could you test if it now works for you.
