### ISSUE TITLE
baseurl changed

### ISSUE THREAD

**Issue by ckluss** [rnuske/vegperiod#2]
Hi 

many thanks for publishing this great package! The DWD changed

ftp://ftp-cdc.dwd.de/pub/CDC/observations_germany/climate to
ftp://opendata.dwd.de/climate_environment/CDC/observations_germany/climate

( https://www.dwd.de/DE/klimaumwelt/cdc/cdc_node.html )

Kind regards
Christof

**Comment by rnuske** [comment]
I guess it's the same problem as issue  #1. this is fixed since 2019-02-03 but not yet submitted to CRAN. could you check with the current github version whether the error still exists?

**Comment by ckluss** [comment]
Seems not to work for me, in https://github.com/rnuske/vegperiod/blob/master/R/read_dwd.R there is a 

` baseURL <- "ftp://ftp-cdc.dwd.de/pub/CDC/observations_germany/climate"
`
but now it should be

` baseURL <- "ftp://opendata.dwd.de/climate_environment/CDC/observations_germany/climate"
`
```
 Die `neuen` Zugriffsadressen sind: https://opendata.dwd.de/climate_environment/CDC/
bzw. ftp://opendata.dwd.de/climate_environment/CDC/.
```

Kind regards
Christof

**Comment by rnuske** [comment]
Thanks for testing. will have a look.

**Comment by rnuske** [comment]
Changed the baseURLs. That was quick fix. Thanks for pointing me in the right direction.

My tests `tests/testthat\test_DWD_stuff.R` all pass now. It's a pity that I had to disable them for CRAN and Travis. Otherwise the CIs would have flagged the issue.

Could you please check if it works for you as well?

**Comment by rnuske** [comment]
checked meticulously. new version on CRAN.
