### ISSUE TITLE
start = 'Menzel': custom parameters

### ISSUE THREAD

**Issue by pschmidtwalter** [rnuske/vegperiod#4]
Hi Robert!

Users of my LWFBroo90R package have fitted custom species' parameters for start-method Menzel, based on recent phenological observations. Could you maybe implement an option (e.g., `species = 'parameters'`), to provide own, custom parameters to predict budburst ? The parameters could also be provided as a named list, e.g.  `species = `list(TbCD, TbH, a, b)` and then become an entry of the `Mp`-list in `.start_menzel()`.

Best regards
Paul

**Comment by rnuske** [comment]
Good idea. I will check how much extra plumbing that idea requires. 

Could you point the inquirer here? I would like to know whether the parameter set is fixed/published and if it is an option to include the parameter set in vegperiod. Are there more frequently changing parameter sets?

**Comment by rnuske** [comment]
closing because of no feedback
