### ISSUE TITLE
Error Message with unsorted but complete dates

### ISSUE THREAD

**Issue by MichaKoe** [rnuske/vegperiod#8]
Hi Robert,

I encountered an unexpected behaviour with vegperiod. If an unsortet but otherwise complete date vector is supplied, your code drops an error message. 

```
require(vegperiod)
data(goe)
goe$shuffel_date<-sample(goe$date)
all(goe$shuffel_date %in% goe$date)

# working
vegperiod(dates=goe$date, Tavg=goe$t,
          start.method="Menzel", end.method="vonWilpert",
          species="Picea abies (frueh)", est.prev=5)

# error message "  Not all years in 'dates' have expected length."
vegperiod(dates=goe$shuffel_date, Tavg=goe$t,
          start.method="Menzel", end.method="vonWilpert",
          species="Picea abies (frueh)", est.prev=5)
```

Best regards

**Comment by rnuske** [comment]
Thanks a lot for the observation. I haven't come across an unsorted time series of temperature data yet. 

The error message is obviously misleading. I am thinking what to do about it and tend to refine the checking to provide a more fitting message. But I do not plan to assume data management tasks for the users of vegperiod.

Cheers
  Robert
